# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/clojure:1.10.3-node

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Install babashka
          command: |
            bash <(curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install) --dir ~
            sudo mv ~/bb /usr/local/bin/bb
      - run:
          name: Install Planck
          command: |
            sudo add-apt-repository ppa:mfikes/planck
            sudo apt-get update
            sudo apt-get install planck
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run tests!
      - run: bb test :1.10
      - run: bb test :1.11

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }} 

      - run: .circleci/maybe-deploy.sh
