# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.8.1-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: Install Clojure
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
            chmod +x linux-install-1.9.0.397.sh
            sudo ./linux-install-1.9.0.397.sh
      - run:
          name: Install Planck
          command: |
            sudo apt-get install javascriptcoregtk-4.0 libzip4
            curl -O http://planck-repl.org/releases/2.19.0-debian-9.0/planck
            curl -O http://planck-repl.org/releases/2.19.0-debian-9.0/plk
            chmod +x planck
            chmod +x plk
            sudo mv planck /usr/bin
            sudo mv plk /usr/bin
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # run tests!
      - run: script/clean
      - run: script/test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }} 

      - run: .circleci/maybe-deploy.sh
